
language: python

python:
  - 3.8

install:
  - pip install -r requirements.txt

script:
  - black ./
  - flake8 ./
  - coverage run --source=. manage.py test

after_script:
   - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "swe1-app"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-east-1-920848894865"
  on:
      branch: main