
language: python

python:
  - 3.7.1

install:
  - pip install -r requirements.txt

script:
  - black --check --exclude migrations .
  - flake8 .

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIA5MZW7BOIYVYW6WOW"
  secret_access_key:
    secure: "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"
  region: "us-east-1"
  app: "django-tutorial"
  env: "django-dev"
  bucket_name: "elasticbeanstalk-us-east-1-djangodev"